import type { Metadata } from "next";
import { Ubuntu, Cherry_Bomb_One } from "next/font/google";
import "./globals.css";

const geistSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Cherry_Bomb_One({
  variable: "--font-cherry_bomb_one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
